package project;

import com.itextpdf.kernel.color.Color;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.border.Border;
import com.itextpdf.layout.border.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.layout.border.DashedBorder;
import com.itextpdf.layout.property.TextAlignment;
import java.io.IOException;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.TableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class Quotition extends javax.swing.JFrame implements ActionListener{
    private double totalmoney;
    private double discount;
    public void cal(){
      //totalnum = Integer.parseInt(pricetext.getText()) * Integer.parseInt(unittext.getText());
    }

    /**
     * Creates new form Quotition
     */
    public Quotition() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        namelabel = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        infolabel = new javax.swing.JLabel();
        ziptext = new javax.swing.JTextField();
        taxidtext = new javax.swing.JTextField();
        officetext = new javax.swing.JTextField();
        totallabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sellerlabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        sellertext = new javax.swing.JTextField();
        datetext = new javax.swing.JTextField();
        Refnumlabel = new javax.swing.JLabel();
        refnumtext = new javax.swing.JTextField();
        detaillabel = new javax.swing.JLabel();
        detailtext = new javax.swing.JTextField();
        projectlabel = new javax.swing.JLabel();
        projecttext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        producttext = new javax.swing.JTextField();
        pricetext = new javax.swing.JTextField();
        quantitytext = new javax.swing.JTextField();
        unittext = new javax.swing.JTextField();
        unitpricetext = new javax.swing.JTextField();
        totalnumnum = new javax.swing.JLabel();
        Numbertext = new javax.swing.JTextField();
        namepricelabel = new javax.swing.JLabel();
        totalpricelabel = new javax.swing.JLabel();
        unitlabel = new javax.swing.JLabel();
        unitpricelabel = new javax.swing.JLabel();
        numlabel = new javax.swing.JLabel();
        quantitylabel = new javax.swing.JLabel();
        namepricelabel1 = new javax.swing.JLabel();
        totalnum = new javax.swing.JLabel();
        addlistbutton = new javax.swing.JButton();
        percentlabel = new javax.swing.JLabel();
        totalmoneylabel = new javax.swing.JLabel();
        totaldiscountlabel = new javax.swing.JLabel();
        alltotallabel = new javax.swing.JLabel();
        alltotalnum = new javax.swing.JLabel();
        totalnumnumnum = new javax.swing.JLabel();
        discountnum = new javax.swing.JLabel();
        totaldiscountnum = new javax.swing.JLabel();
        discountlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infotext = new javax.swing.JTextArea();
        discounttext = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        taxidlabel = new javax.swing.JLabel();
        ziplabel = new javax.swing.JLabel();
        officelabel = new javax.swing.JLabel();
        serielabel = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        headerlabel = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        namelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelabel.setText("Name:");

        nametext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametext.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });

        infolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infolabel.setText("Customer Information:");

        ziptext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ziptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ziptextActionPerformed(evt);
            }
        });

        taxidtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taxidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxidtextActionPerformed(evt);
            }
        });

        officetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        officetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officetextActionPerformed(evt);
            }
        });

        totallabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totallabel.setText("Total:");

        sellerlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellerlabel.setText("Seller:");

        datelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datelabel.setText("Date:");

        sellertext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellertextActionPerformed(evt);
            }
        });

        datetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetextActionPerformed(evt);
            }
        });

        Refnumlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Refnumlabel.setText("Ref:");

        refnumtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refnumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refnumtextActionPerformed(evt);
            }
        });

        detaillabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        detaillabel.setText("Details:");

        detailtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        detailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailtextActionPerformed(evt);
            }
        });

        projectlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        projectlabel.setText("Project:");

        projecttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        projecttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projecttextActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        producttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        producttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producttextActionPerformed(evt);
            }
        });

        pricetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pricetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetextActionPerformed(evt);
            }
        });

        quantitytext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantitytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytextActionPerformed(evt);
            }
        });

        unittext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unittext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unittextActionPerformed(evt);
            }
        });

        unitpricetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unitpricetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpricetextActionPerformed(evt);
            }
        });

        totalnumnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalnumnum.setText("0.00");

        Numbertext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Numbertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbertextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Numbertext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(producttext, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(pricetext))
                .addGap(53, 53, 53)
                .addComponent(quantitytext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(unittext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(unitpricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(totalnumnum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(producttext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitpricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unittext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantitytext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalnumnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Numbertext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        namepricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namepricelabel.setText("Product");

        totalpricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalpricelabel.setText("Total");

        unitlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unitlabel.setText("๊Unit");

        unitpricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unitpricelabel.setText(" Unit price");

        numlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numlabel.setText("No.");

        quantitylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantitylabel.setText("Quantity");

        namepricelabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namepricelabel1.setText("Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(numlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(namepricelabel)
                .addGap(115, 115, 115)
                .addComponent(namepricelabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(quantitylabel)
                .addGap(111, 111, 111)
                .addComponent(unitlabel)
                .addGap(137, 137, 137)
                .addComponent(unitpricelabel)
                .addGap(101, 101, 101)
                .addComponent(totalpricelabel)
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namepricelabel)
                    .addComponent(totalpricelabel)
                    .addComponent(unitlabel)
                    .addComponent(unitpricelabel)
                    .addComponent(numlabel)
                    .addComponent(quantitylabel)
                    .addComponent(namepricelabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        totalnum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        totalnum.setText("0.00");

        addlistbutton.setBackground(new java.awt.Color(102, 102, 255));
        addlistbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addlistbutton.setForeground(new java.awt.Color(255, 255, 255));
        addlistbutton.setText("ADD+");
        addlistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlistbuttonActionPerformed(evt);
            }
        });

        percentlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        percentlabel.setText("%");

        totalmoneylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalmoneylabel.setText("Total Money:");

        totaldiscountlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaldiscountlabel.setText("Total Discount:");

        alltotallabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alltotallabel.setForeground(new java.awt.Color(255, 51, 51));
        alltotallabel.setText("Overall:");

        alltotalnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alltotalnum.setForeground(new java.awt.Color(255, 0, 0));
        alltotalnum.setText("0.00");

        totalnumnumnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalnumnumnum.setText("0.00");

        discountnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        discountnum.setText("0.00");

        totaldiscountnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totaldiscountnum.setText("0.00");

        discountlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discountlabel.setText("Discount:");

        infotext.setColumns(20);
        infotext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infotext.setRows(5);
        jScrollPane1.setViewportView(infotext);

        discounttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discounttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discounttextActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Product", "Price", "Quatity", "Unit", "Unitprice", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        taxidlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taxidlabel.setText("TaxID:");

        ziplabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ziplabel.setText("Zip:");

        officelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        officelabel.setText("Office:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1074, 1074, 1074)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(discountlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(discounttext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(percentlabel))
                                    .addComponent(totaldiscountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alltotallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalnumnumnum, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(discountnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totaldiscountnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alltotalnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(detaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(detailtext))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addlistbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(projectlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(projecttext, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(Refnumlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(refnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(60, 60, 60))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taxidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ziplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(officelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taxidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ziptext, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(officetext, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(infolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(totalnum, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sellerlabel)
                                    .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datetext, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sellertext, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(36, 36, 36))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(namelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infolabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(totallabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalnum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datelabel)
                            .addComponent(datetext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sellerlabel)
                            .addComponent(sellertext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(officetext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(officelabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ziptext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ziplabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxidlabel))
                        .addGap(39, 39, 39)))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Refnumlabel)
                    .addComponent(refnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectlabel)
                    .addComponent(projecttext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detaillabel)
                    .addComponent(detailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addlistbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalnumnumnum)
                    .addComponent(totalmoneylabel))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountlabel)
                            .addComponent(percentlabel)
                            .addComponent(discounttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountnum))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totaldiscountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaldiscountnum))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alltotallabel)
                            .addComponent(alltotalnum)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        serielabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        serielabel.setText("Receipt");

        savebutton.setBackground(new java.awt.Color(51, 204, 0));
        savebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        savebutton.setForeground(new java.awt.Color(255, 255, 255));
        savebutton.setText("บันทึกเอกสาร");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        headerlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        closebutton.setBackground(new java.awt.Color(255, 0, 51));
        closebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("ปิดหน้าต่าง");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(serielabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 724, Short.MAX_VALUE)
                .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(headerlabel)
                        .addGap(18, 18, 18)
                        .addComponent(serielabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addlistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlistbuttonActionPerformed
        // TODO add your handling code here:
        totalnumnum.setText(String.valueOf(Double.parseDouble(pricetext.getText()) * Double.parseDouble(unittext.getText())));
        totalmoney = (totalmoney + Double.parseDouble(pricetext.getText()) * Double.parseDouble(unittext.getText()));
        totalnumnumnum.setText(String.valueOf(totalmoney));
        
        discount=totalmoney * ((Double.parseDouble(discounttext.getText())) / 100);
        discountnum.setText(String.valueOf(discount));
        
        totaldiscountnum.setText(String.valueOf(totalmoney - (totalmoney * (Double.parseDouble(discounttext.getText())/100))));
        
        alltotalnum.setText(totaldiscountnum.getText());
        
        totalnum.setText(alltotalnum.getText());
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new String[]{Numbertext.getText(), producttext.getText(), pricetext.getText(), quantitytext.getText(), unittext.getText(), unitpricetext.getText(), totalnumnum.getText()});
        
     
        
        Numbertext.setText("");
        producttext.setText("");
        pricetext.setText("");
        quantitytext.setText("");
        unittext.setText("");
        unitpricetext.setText("");
        totalnumnum.setText("0.00");
    }//GEN-LAST:event_addlistbuttonActionPerformed

    private void officetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officetextActionPerformed

    private void taxidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxidtextActionPerformed

    private void ziptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ziptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ziptextActionPerformed

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void sellertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellertextActionPerformed

    private void datetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetextActionPerformed

    private void refnumtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refnumtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refnumtextActionPerformed

    private void detailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailtextActionPerformed

    private void projecttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projecttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projecttextActionPerformed

    private void producttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producttextActionPerformed

    private void pricetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetextActionPerformed

    private void quantitytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytextActionPerformed

    private void unittextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unittextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unittextActionPerformed

    private void unitpricetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpricetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpricetextActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        // TODO add your handling code here:
        //Home registerForm = new Home();//
        //registerForm.setVisible(true);//
        //closebutton.addActionListener(new Quotition());//      
    }//GEN-LAST:event_closebuttonActionPerformed

    private void NumbertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumbertextActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        String path = "Quotition.pdf";
        PdfWriter pdfWriter = null;
        try {
            pdfWriter = new PdfWriter(path);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Quotition.class.getName()).log(Level.SEVERE, null, ex);
        }
        PdfDocument pdfDocument = new PdfDocument(pdfWriter);
        pdfDocument.setDefaultPageSize(PageSize.A4);
        Document document = new Document(pdfDocument);
        
       
        
        float threecol = 190f;
        float twocol=285f;
        float twocol150 = twocol+150f;
        float twocolumnWidth[]={twocol150, twocol};
        float fullwidth[]={threecol*3};
        float sixColumnWidth[] = {threecol, threecol, threecol, threecol, threecol, threecol, threecol};
        Paragraph space = new Paragraph("\n");
        
        Table table=new Table(twocolumnWidth);
        table.addCell(new Cell().add(serielabel.getText()).setFontSize(30f).setBorder(Border.NO_BORDER).setBold());
        
        Border bd = new SolidBorder(Color.RED, 2f);
        Table divider = new Table(fullwidth);
        divider.setBorder(bd);
        
        document.add(table);
        document.add(space);
        document.add(divider);
        document.add(space);
        
        
        Table nameColTable = new Table(twocolumnWidth);
        nameColTable.addCell(new Cell().add(namelabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        document.add(nameColTable);
        
        Table nametxtColTable = new Table(twocolumnWidth);
        nametxtColTable.addCell(new Cell().add(nametext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        document.add(nametxtColTable);
        
        Table customerColTable = new Table(twocolumnWidth);
        customerColTable.addCell(new Cell().add(infolabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        document.add(space);
        document.add(customerColTable);
        
        Table customertxtColTable = new Table(twocolumnWidth);
        customertxtColTable.addCell(new Cell().add(infotext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        customertxtColTable.addCell(new Cell().add(totallabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        document.add(customertxtColTable);
        
        Table zipColTable = new Table(twocolumnWidth);
        zipColTable.addCell(new Cell().add(ziptext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        zipColTable.addCell(new Cell().add(totalnum.getText()).setFontSize(30f).setBorder(Border.NO_BORDER).setBold());
        document.add(zipColTable);
        
        Table bigColTable = new Table(twocolumnWidth);
        Table nestedTable2 = new Table(new float[]{twocol/2, twocol/2});
        nestedTable2.addCell(new Cell().add(taxidtext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable2.addCell(new Cell().add("").setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable2.addCell(new Cell().add(officetext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        
        Table nestedTable = new Table(new float[]{twocol/2, twocol/2});
        nestedTable.addCell(new Cell().add(datelabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        nestedTable.addCell(new Cell().add(datetext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable.addCell(new Cell().add(sellerlabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        nestedTable.addCell(new Cell().add(sellertext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        
        bigColTable.addCell(new Cell().add(nestedTable2).setBorder(Border.NO_BORDER));
        bigColTable.addCell(new Cell().add(nestedTable).setBorder(Border.NO_BORDER));
        document.add(bigColTable);
        
        Table tableDivider2 = new Table(fullwidth);
        Border pointline = new DashedBorder(Color.RED, 0.5f);
        document.add(space);
        document.add(tableDivider2.setBorder(pointline));
        
        Table bigColTable2 = new Table(twocolumnWidth);
        Table nestedTable3 = new Table(new float[]{twocol/2, twocol/2});
        nestedTable3.addCell(new Cell().add(projectlabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        nestedTable3.addCell(new Cell().add(projecttext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable3.addCell(new Cell().add(detaillabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        nestedTable3.addCell(new Cell().add(detailtext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        
        Table nestedTable4 = new Table(new float[]{twocol/2, twocol/2});
        nestedTable4.addCell(new Cell().add(Refnumlabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER).setBold());
        nestedTable4.addCell(new Cell().add(refnumtext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable4.addCell(new Cell().add("").setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable4.addCell(new Cell().add("").setFontSize(12f).setBorder(Border.NO_BORDER));
        
        bigColTable2.addCell(new Cell().add(nestedTable3).setBorder(Border.NO_BORDER));
        bigColTable2.addCell(new Cell().add(nestedTable4).setBorder(Border.NO_BORDER));
        document.add(bigColTable2);
        
        Table sixColTable = new Table(sixColumnWidth);
        sixColTable.setBackgroundColor(Color.RED, 0.8f);
        sixColTable.addCell(new Cell().add(numlabel.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        sixColTable.addCell(new Cell().add(namepricelabel.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        sixColTable.addCell(new Cell().add(namepricelabel1.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        sixColTable.addCell(new Cell().add(quantitylabel.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        sixColTable.addCell(new Cell().add(unitlabel.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        sixColTable.addCell(new Cell().add(unitpricelabel.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        sixColTable.addCell(new Cell().add(totalpricelabel.getText()).setBorder(Border.NO_BORDER).setFontColor(Color.WHITE).setBold());
        document.add(space);
        document.add(sixColTable);
        
        Table nestedlistTable = new Table(new float[]{twocol/2, twocol/2});
        nestedlistTable.addCell(new Cell().add(producttext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedlistTable.addCell(new Cell().add(pricetext.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedlistTable.addCell(new Cell().add("").setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedlistTable.addCell(new Cell().add("").setFontSize(12f).setBorder(Border.NO_BORDER));
        
        Table itemColTable1 = new Table(sixColumnWidth);
        TableModel model = jTable2.getModel();
        for(int i = 0; i < model.getRowCount(); i++){
            for(int j = 0; j < model.getColumnCount(); j++){
            itemColTable1.addCell(new Cell().add(model.getValueAt(i, j).toString()).setFontSize(12f).setBorder(Border.NO_BORDER));
        }
        }
        
        document.add(itemColTable1);
        
        Table lowerColTable = new Table(twocolumnWidth);
        Table nestedTable5 = new Table(new float[]{twocol/2, twocol/2});
        nestedTable5.addCell(new Cell().add(totalmoneylabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(totalnumnumnum.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(discountlabel.getText() + discounttext.getText() + percentlabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(discountnum.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(totaldiscountlabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(totaldiscountnum.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(alltotallabel.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        nestedTable5.addCell(new Cell().add(alltotalnum.getText()).setFontSize(12f).setBorder(Border.NO_BORDER));
        
        lowerColTable.addCell(new Cell().add("").setBorder(Border.NO_BORDER));
        lowerColTable.addCell(new Cell().add(nestedTable5).setBorder(Border.NO_BORDER));
        
        document.add(space);
        document.add(lowerColTable);
        
        document.close();
        System.out.println("PDF created");
        

    }//GEN-LAST:event_savebuttonActionPerformed

    private void discounttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discounttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discounttextActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
// create UI here...
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Quotition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Numbertext;
    private javax.swing.JLabel Refnumlabel;
    private javax.swing.JButton addlistbutton;
    private javax.swing.JLabel alltotallabel;
    private javax.swing.JLabel alltotalnum;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField datetext;
    private javax.swing.JLabel detaillabel;
    private javax.swing.JTextField detailtext;
    private javax.swing.JLabel discountlabel;
    private javax.swing.JLabel discountnum;
    private javax.swing.JTextField discounttext;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel infolabel;
    private javax.swing.JTextArea infotext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel namepricelabel;
    private javax.swing.JLabel namepricelabel1;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel numlabel;
    private javax.swing.JLabel officelabel;
    private javax.swing.JTextField officetext;
    private javax.swing.JLabel percentlabel;
    private javax.swing.JTextField pricetext;
    private javax.swing.JTextField producttext;
    private javax.swing.JLabel projectlabel;
    private javax.swing.JTextField projecttext;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JTextField quantitytext;
    private javax.swing.JTextField refnumtext;
    private javax.swing.JButton savebutton;
    private javax.swing.JLabel sellerlabel;
    private javax.swing.JTextField sellertext;
    private javax.swing.JLabel serielabel;
    private javax.swing.JLabel taxidlabel;
    private javax.swing.JTextField taxidtext;
    private javax.swing.JLabel totaldiscountlabel;
    private javax.swing.JLabel totaldiscountnum;
    private javax.swing.JLabel totallabel;
    private javax.swing.JLabel totalmoneylabel;
    private javax.swing.JLabel totalnum;
    private javax.swing.JLabel totalnumnum;
    private javax.swing.JLabel totalnumnumnum;
    private javax.swing.JLabel totalpricelabel;
    private javax.swing.JLabel unitlabel;
    private javax.swing.JLabel unitpricelabel;
    private javax.swing.JTextField unitpricetext;
    private javax.swing.JTextField unittext;
    private javax.swing.JLabel ziplabel;
    private javax.swing.JTextField ziptext;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
