/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.JPopupMenu;

public class Home extends javax.swing.JFrame{

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents(); 
        setLocationRelativeTo(null);
    }
    
    private void setButtonIconAndColor() {
    Document.setFont(new java.awt.Font("Segoe UI", 1, 15));
    Document.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png")));
    Document.setText("<html><font color='#007bff'>Home</font></html>");
    Document.setBorderPainted(false);
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        SelectHome = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usethisDashboard = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Document = new javax.swing.JButton();
        Project = new javax.swing.JButton();
        Reporting = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        Tax = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Setting = new javax.swing.JButton();
        UserName = new javax.swing.JLabel();
        EmailUser = new javax.swing.JLabel();
        ProfileUser = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 1020));

        jPanel1.setLayout(new java.awt.BorderLayout());

        SelectHome.setBackground(new java.awt.Color(255, 255, 255));
        SelectHome.setPreferredSize(new java.awt.Dimension(340, 1020));

        jSeparator1.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator1.setForeground(new java.awt.Color(136, 136, 136));

        usethisDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usethisDashboard.setText("Usethis Dashboard");

        Home.setBackground(new java.awt.Color(224, 227, 232));
        Home.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png"))); // NOI18N
        Home.setText("   Home");
        Home.setBorderPainted(false);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.setMaximumSize(new java.awt.Dimension(342, 966));
        Home.setPreferredSize(new java.awt.Dimension(966, 342));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Document.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Document.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_page-edit.png"))); // NOI18N
        Document.setText("   Document");
        Document.setBorderPainted(false);
        Document.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Document.setMaximumSize(new java.awt.Dimension(342, 966));
        Document.setPreferredSize(new java.awt.Dimension(966, 342));
        Document.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DocumentMouseClicked(evt);
            }
        });
        Document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentActionPerformed(evt);
            }
        });

        Project.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Project.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_app-window.png"))); // NOI18N
        Project.setText("    Project");
        Project.setBorderPainted(false);
        Project.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Project.setMaximumSize(new java.awt.Dimension(342, 966));
        Project.setPreferredSize(new java.awt.Dimension(966, 342));
        Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectActionPerformed(evt);
            }
        });

        Reporting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Reporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_stats-report.png"))); // NOI18N
        Reporting.setText("   Reporting");
        Reporting.setBorderPainted(false);
        Reporting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Reporting.setMaximumSize(new java.awt.Dimension(342, 966));
        Reporting.setPreferredSize(new java.awt.Dimension(966, 342));
        Reporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportingActionPerformed(evt);
            }
        });

        Users.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_user-square.png"))); // NOI18N
        Users.setText("   Users");
        Users.setBorderPainted(false);
        Users.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Users.setMaximumSize(new java.awt.Dimension(342, 966));
        Users.setPreferredSize(new java.awt.Dimension(966, 342));
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });

        Tax.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Tax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_settings.png"))); // NOI18N
        Tax.setText("  Setting");
        Tax.setBorderPainted(false);
        Tax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tax.setMaximumSize(new java.awt.Dimension(342, 966));
        Tax.setPreferredSize(new java.awt.Dimension(966, 342));
        Tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxActionPerformed(evt);
            }
        });

        Icon.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Logo.png.png")); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator2.setForeground(new java.awt.Color(136, 136, 136));

        Setting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_calculator.png"))); // NOI18N
        Setting.setText("   Tax");
        Setting.setToolTipText("");
        Setting.setBorderPainted(false);
        Setting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Setting.setMaximumSize(new java.awt.Dimension(342, 966));
        Setting.setPreferredSize(new java.awt.Dimension(966, 342));
        Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingActionPerformed(evt);
            }
        });

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserName.setText("Username");

        EmailUser.setForeground(new java.awt.Color(136, 136, 136));
        EmailUser.setText("Email");

        ProfileUser.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Ellipse 2 (1).png")); // NOI18N

        javax.swing.GroupLayout SelectHomeLayout = new javax.swing.GroupLayout(SelectHome);
        SelectHome.setLayout(SelectHomeLayout);
        SelectHomeLayout.setHorizontalGroup(
            SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(SelectHomeLayout.createSequentialGroup()
                .addGroup(SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectHomeLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usethisDashboard))
                    .addGroup(SelectHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProfileUser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserName)
                            .addComponent(EmailUser)))
                    .addGroup(SelectHomeLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Reporting, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Project, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        SelectHomeLayout.setVerticalGroup(
            SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectHomeLayout.createSequentialGroup()
                .addGroup(SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectHomeLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usethisDashboard)
                        .addGap(42, 42, 42)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Project, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reporting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SelectHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectHomeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailUser))
                    .addGroup(SelectHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ProfileUser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        Icon.getAccessibleContext().setAccessibleName("LOGO");

        jPanel1.add(SelectHome, java.awt.BorderLayout.WEST);

        Dashboard.setBackground(new java.awt.Color(236, 239, 243));

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );

        jPanel1.add(Dashboard, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingActionPerformed

    private void TaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsersActionPerformed

    private void ReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportingActionPerformed

    private void ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectActionPerformed

    private void DocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentActionPerformed

    private void DocumentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DocumentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentMouseClicked

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton Document;
    private javax.swing.JLabel EmailUser;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel ProfileUser;
    private javax.swing.JButton Project;
    private javax.swing.JButton Reporting;
    private javax.swing.JPanel SelectHome;
    private javax.swing.JButton Setting;
    private javax.swing.JButton Tax;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton Users;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel usethisDashboard;
    // End of variables declaration//GEN-END:variables

}
