/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import org.jfree.chart.*;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author aruch
 */
public class Home extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form Homee
     */
    public Home() {
        initComponents(); 
        setLocationRelativeTo(null);
        try {
            DBConnect db = new DBConnect();
            ResultSet rs = null;

            String nam = db.getName(UserDatabase.key);
            
            rs = db.getQuote(UserDatabase.key);
            if (rs.next()) {
                String wait = rs.getString("Waiting");
                String accept = rs.getString("Accepted");
                String projDone = rs.getString("ProjectDone");
                
                LabelNumberDarkblue13.setText(wait);
                LabelNumberBlue.setText(accept);
                LabelNumberRed1.setText(projDone);
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        showLineChart();
        showPieChart();
        ope();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        NavBarHome = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usethisDashboard = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserName = new javax.swing.JLabel();
        EmailUser = new javax.swing.JLabel();
        BottomProfileUserHome = new javax.swing.JLabel();
        DocumentButton = new javax.swing.JPanel();
        IconDocument = new javax.swing.JLabel();
        DocumentCombobox = new javax.swing.JComboBox<>();
        jButtonProject = new javax.swing.JButton();
        jbuttonReporting = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonTax = new javax.swing.JButton();
        jButtonSetting = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TopProfileHome = new javax.swing.JPanel();
        ProfielUserHome = new javax.swing.JLabel();
        NumberUserHome = new javax.swing.JLabel();
        DateHomePanel = new javax.swing.JLabel();
        IconBellHome = new javax.swing.JLabel();
        WelcomebackUsername = new javax.swing.JLabel();
        HereWhatGoing = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        NumberPanelDarkblue13 = new javax.swing.JPanel();
        IconDarkblue13 = new javax.swing.JLabel();
        LabelNumberDarkblue13 = new javax.swing.JLabel();
        TextDarkblue13 = new javax.swing.JTextField();
        IconBlue13 = new javax.swing.JLabel();
        NumberPanelBlue = new javax.swing.JPanel();
        LabelNumberBlue = new javax.swing.JLabel();
        TextBlue = new javax.swing.JTextField();
        IconBlue14 = new javax.swing.JLabel();
        NumberPanelRed1 = new javax.swing.JPanel();
        IconRed1 = new javax.swing.JLabel();
        LabelNumberRed1 = new javax.swing.JLabel();
        TextRed1 = new javax.swing.JTextField();
        EmptyPanelTopLeft = new javax.swing.JPanel();
        EmptyPanelTopRight = new javax.swing.JPanel();
        EmptyPanelBottomLeft = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        WelcomebackUsername1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        EmptyPanelBottomRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavBarHome.setBackground(new java.awt.Color(255, 255, 255));
        NavBarHome.setPreferredSize(new java.awt.Dimension(340, 1020));

        jSeparator1.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator1.setForeground(new java.awt.Color(136, 136, 136));

        usethisDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usethisDashboard.setText("Usethis Dashboard");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png.png"))); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator2.setForeground(new java.awt.Color(136, 136, 136));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserName.setText("Username");

        EmailUser.setForeground(new java.awt.Color(136, 136, 136));
        EmailUser.setText("Email");

        DocumentButton.setBackground(new java.awt.Color(255, 255, 255));

        IconDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_page-edit.png"))); // NOI18N

        DocumentCombobox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        DocumentCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Quotation", "Recipt" }));
        DocumentCombobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        DocumentCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DocumentButtonLayout = new javax.swing.GroupLayout(DocumentButton);
        DocumentButton.setLayout(DocumentButtonLayout);
        DocumentButtonLayout.setHorizontalGroup(
            DocumentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(IconDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DocumentCombobox, 0, 269, Short.MAX_VALUE))
        );
        DocumentButtonLayout.setVerticalGroup(
            DocumentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DocumentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DocumentCombobox)
                    .addGroup(DocumentButtonLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(IconDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButtonProject.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_app-window.png"))); // NOI18N
        jButtonProject.setText("  Project");
        jButtonProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjectActionPerformed(evt);
            }
        });

        jbuttonReporting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jbuttonReporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_stats-report.png"))); // NOI18N
        jbuttonReporting.setText("  Reporting");
        jbuttonReporting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbuttonReporting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbuttonReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonReportingActionPerformed(evt);
            }
        });

        jButtonUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_user-square.png"))); // NOI18N
        jButtonUser.setText("  Users");
        jButtonUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });

        jButtonTax.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_calculator.png"))); // NOI18N
        jButtonTax.setText("  Tax");
        jButtonTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonTax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxActionPerformed(evt);
            }
        });

        jButtonSetting.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_settings.png"))); // NOI18N
        jButtonSetting.setText("  Setting");
        jButtonSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingActionPerformed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(224, 227, 232));
        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png"))); // NOI18N
        jButtonHome.setText("  Home");
        jButtonHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarHomeLayout = new javax.swing.GroupLayout(NavBarHome);
        NavBarHome.setLayout(NavBarHomeLayout);
        NavBarHomeLayout.setHorizontalGroup(
            NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(NavBarHomeLayout.createSequentialGroup()
                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarHomeLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usethisDashboard))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarHomeLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(BottomProfileUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserName)
                                .addComponent(EmailUser)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarHomeLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(DocumentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(NavBarHomeLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbuttonReporting, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                .addComponent(jButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        NavBarHomeLayout.setVerticalGroup(
            NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarHomeLayout.createSequentialGroup()
                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarHomeLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usethisDashboard)
                        .addGap(42, 42, 42)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarHomeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailUser))
                    .addGroup(NavBarHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BottomProfileUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        TopProfileHome.setBackground(new java.awt.Color(255, 255, 255));

        ProfielUserHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ellipse 2 (1).png"))); // NOI18N

        NumberUserHome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NumberUserHome.setText("Number");

        javax.swing.GroupLayout TopProfileHomeLayout = new javax.swing.GroupLayout(TopProfileHome);
        TopProfileHome.setLayout(TopProfileHomeLayout);
        TopProfileHomeLayout.setHorizontalGroup(
            TopProfileHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopProfileHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfielUserHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumberUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        TopProfileHomeLayout.setVerticalGroup(
            TopProfileHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopProfileHomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(TopProfileHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopProfileHomeLayout.createSequentialGroup()
                        .addComponent(ProfielUserHome)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopProfileHomeLayout.createSequentialGroup()
                        .addComponent(NumberUserHome)
                        .addGap(28, 28, 28))))
        );

        DateHomePanel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DateHomePanel.setForeground(new java.awt.Color(136, 136, 136));
        DateHomePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circum_calendar-date.png"))); // NOI18N
        DateHomePanel.setText("Friday, July 10,2024");

        IconBellHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ph_bell.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconBellHome)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateHomePanel)
                    .addComponent(TopProfileHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TopProfileHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DateHomePanel)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(IconBellHome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        WelcomebackUsername.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        WelcomebackUsername.setText("Welcome back, Username");

        HereWhatGoing.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        HereWhatGoing.setForeground(new java.awt.Color(163, 165, 171));
        HereWhatGoing.setText("Here’s what’s going on with your company status.");

        NumberPanelDarkblue13.setBackground(new java.awt.Color(255, 255, 255));
        NumberPanelDarkblue13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        IconDarkblue13.setBackground(new java.awt.Color(255, 255, 255));

        LabelNumberDarkblue13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNumberDarkblue13.setText("1");

        TextDarkblue13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextDarkblue13.setForeground(new java.awt.Color(136, 136, 136));
        TextDarkblue13.setText("Waiting");
        TextDarkblue13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextDarkblue13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDarkblue13ActionPerformed(evt);
            }
        });

        IconBlue13.setBackground(new java.awt.Color(255, 255, 255));
        IconBlue13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 45.png"))); // NOI18N

        javax.swing.GroupLayout NumberPanelDarkblue13Layout = new javax.swing.GroupLayout(NumberPanelDarkblue13);
        NumberPanelDarkblue13.setLayout(NumberPanelDarkblue13Layout);
        NumberPanelDarkblue13Layout.setHorizontalGroup(
            NumberPanelDarkblue13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelDarkblue13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconDarkblue13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IconBlue13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NumberPanelDarkblue13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextDarkblue13)
                    .addComponent(LabelNumberDarkblue13, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        NumberPanelDarkblue13Layout.setVerticalGroup(
            NumberPanelDarkblue13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumberPanelDarkblue13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNumberDarkblue13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextDarkblue13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(NumberPanelDarkblue13Layout.createSequentialGroup()
                .addGroup(NumberPanelDarkblue13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberPanelDarkblue13Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconDarkblue13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelDarkblue13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconBlue13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NumberPanelBlue.setBackground(new java.awt.Color(255, 255, 255));
        NumberPanelBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        LabelNumberBlue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNumberBlue.setText("0");

        TextBlue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextBlue.setForeground(new java.awt.Color(136, 136, 136));
        TextBlue.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextBlue.setText("Accept");
        TextBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBlueActionPerformed(evt);
            }
        });

        IconBlue14.setBackground(new java.awt.Color(255, 255, 255));
        IconBlue14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 45 (1).png"))); // NOI18N

        javax.swing.GroupLayout NumberPanelBlueLayout = new javax.swing.GroupLayout(NumberPanelBlue);
        NumberPanelBlue.setLayout(NumberPanelBlueLayout);
        NumberPanelBlueLayout.setHorizontalGroup(
            NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextBlue, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(LabelNumberBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(IconBlue14)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );
        NumberPanelBlueLayout.setVerticalGroup(
            NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LabelNumberBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(IconBlue14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        NumberPanelRed1.setBackground(new java.awt.Color(255, 255, 255));
        NumberPanelRed1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        IconRed1.setBackground(new java.awt.Color(255, 255, 255));
        IconRed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 45 (2).png"))); // NOI18N

        LabelNumberRed1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNumberRed1.setText("2");

        TextRed1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextRed1.setForeground(new java.awt.Color(136, 136, 136));
        TextRed1.setText("Project Done");
        TextRed1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRed1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumberPanelRed1Layout = new javax.swing.GroupLayout(NumberPanelRed1);
        NumberPanelRed1.setLayout(NumberPanelRed1Layout);
        NumberPanelRed1Layout.setHorizontalGroup(
            NumberPanelRed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelRed1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconRed1)
                .addGap(18, 18, 18)
                .addGroup(NumberPanelRed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextRed1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(LabelNumberRed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        NumberPanelRed1Layout.setVerticalGroup(
            NumberPanelRed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelRed1Layout.createSequentialGroup()
                .addGroup(NumberPanelRed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberPanelRed1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconRed1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelRed1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelNumberRed1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextRed1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        EmptyPanelTopLeft.setBackground(new java.awt.Color(255, 255, 255));
        EmptyPanelTopLeft.setLayout(new java.awt.BorderLayout());

        EmptyPanelTopRight.setBackground(new java.awt.Color(255, 255, 255));
        EmptyPanelTopRight.setLayout(new java.awt.BorderLayout());

        EmptyPanelBottomLeft.setBackground(new java.awt.Color(255, 255, 255));

        WelcomebackUsername1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WelcomebackUsername1.setText("Reminder");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout EmptyPanelBottomLeftLayout = new javax.swing.GroupLayout(EmptyPanelBottomLeft);
        EmptyPanelBottomLeft.setLayout(EmptyPanelBottomLeftLayout);
        EmptyPanelBottomLeftLayout.setHorizontalGroup(
            EmptyPanelBottomLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmptyPanelBottomLeftLayout.createSequentialGroup()
                .addGroup(EmptyPanelBottomLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmptyPanelBottomLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(EmptyPanelBottomLeftLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(WelcomebackUsername1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EmptyPanelBottomLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EmptyPanelBottomLeftLayout.setVerticalGroup(
            EmptyPanelBottomLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmptyPanelBottomLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomebackUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        EmptyPanelBottomRight.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyPanelBottomRightLayout = new javax.swing.GroupLayout(EmptyPanelBottomRight);
        EmptyPanelBottomRight.setLayout(EmptyPanelBottomRightLayout);
        EmptyPanelBottomRightLayout.setHorizontalGroup(
            EmptyPanelBottomRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EmptyPanelBottomRightLayout.setVerticalGroup(
            EmptyPanelBottomRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(NumberPanelDarkblue13, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumberPanelRed1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                            .addComponent(EmptyPanelBottomLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(EmptyPanelBottomRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel17Layout.createSequentialGroup()
                            .addComponent(EmptyPanelTopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EmptyPanelTopRight, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberPanelRed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberPanelDarkblue13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmptyPanelTopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmptyPanelTopRight, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(EmptyPanelBottomLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EmptyPanelBottomRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(HereWhatGoing)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(WelcomebackUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WelcomebackUsername)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HereWhatGoing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(NavBarHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavBarHome, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentComboboxActionPerformed
        String selectedDocument = (String) DocumentCombobox.getSelectedItem();
        switch (selectedDocument) {
        case "Document":
            break;
        case "Quotation":
            openQuotition();
            break;
        case "Recipt":
            openReceipt();
            break;
        default:
            break;
    }

    }//GEN-LAST:event_DocumentComboboxActionPerformed
private void openQuotition() {
    Quotition registerForm = new Quotition();
    registerForm.setVisible(true);
    }
private void openReceipt() {
    Receipt registerForm = new Receipt();
    registerForm.setVisible(true);
    }
    private void jButtonProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjectActionPerformed
        Project registerForm = new Project();
        registerForm.setVisible(true);
        jButtonProject.addActionListener(new Home());
        Project pj = new Project();
        pj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonProjectActionPerformed

    private void jbuttonReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonReportingActionPerformed
        Report pj = new Report();
           Report registerForm = new Report();
        registerForm.setVisible(true);
        jbuttonReporting.addActionListener(new Home());
        pj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbuttonReportingActionPerformed

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jButtonTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTaxActionPerformed

    private void jButtonSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSettingActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
         Home registerForm = new Home();
        registerForm.setVisible(true);
        jButtonHome.addActionListener(new Home());
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void TextDarkblue13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDarkblue13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDarkblue13ActionPerformed

    private void TextBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBlueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBlueActionPerformed

    private void TextRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRed1ActionPerformed

    public void showLineChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        ResultSet rs = null;
        double[] months = new double[12];
        String[] monthNames = {"jan", "feb", "mar", "apr", "may", "june", "july", "aug", "sept", "octo", "nov", "dece"};
        String[] monthNames2 = {"Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"};

        
        try {
            DBConnect db = new DBConnect();
            rs = db.getMonthSale(UserDatabase.key);
            
            while (rs.next()) {
                for (int i = 0; i < monthNames.length; i++) {
                    months[i] += Double.parseDouble(rs.getString(monthNames[i]));
                }
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }

        for (int i = 0; i < monthNames.length; i++) {
            dataset.setValue(months[i], "amount", monthNames2[i]);
        }
        
        JFreeChart Chart = ChartFactory.createBarChart("Monthly Sales", "Monthly", "Amount", dataset, PlotOrientation.VERTICAL.VERTICAL, false, true, false);
    
        CategoryPlot Category = Chart.getCategoryPlot();
        Category.setBackgroundPaint(Color.white);
        
        BarRenderer Renderer = (BarRenderer) Category.getRenderer();
        Color ChartColor = new Color(74, 134, 228);
        Renderer.setSeriesPaint(0, ChartColor);
        
        ChartPanel ChartPanel = new ChartPanel(Chart);
        EmptyPanelTopRight.removeAll();
        EmptyPanelTopRight.add(ChartPanel, BorderLayout.CENTER);
        EmptyPanelTopRight.validate();
    }
 
    public void showPieChart() {
        
        DefaultPieDataset dataset = new DefaultPieDataset();

        ResultSet rs = null;
        ArrayList<String> item = new ArrayList<String>();

        String[] hexColors = {"#4A86E4", "#222683", "#D377F3", "#1D1F24", "#3A3D44", "#429482", "#459CED", "#5D923D", "#6B6E75", "#7662EA", "#E55D57", "#EF746D"};
        Color[] colors = new Color[hexColors.length];

        for (int i = 0; i < hexColors.length; i++) {
            try {
                colors[i] = Color.decode(hexColors[i]);
            } catch (NumberFormatException e) {
                e.printStackTrace();
                colors[i] = Color.BLACK;
            }
        }
        
        try {
            DBConnect db = new DBConnect();
            rs = db.getNameItem(UserDatabase.key);
            
            while (rs.next()) {
                dataset.setValue(rs.getString("item"), Integer.parseInt(rs.getString("sales")));
                item.add(rs.getString("item"));
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        JFreeChart pieChart = ChartFactory.createPieChart("Top Sales", dataset, false, true, false);
    
        PiePlot piePlot = (PiePlot) pieChart.getPlot();
        piePlot.setBackgroundPaint(Color.white);
        
        for (int i = 0; i < item.size(); i++) {
            piePlot.setSectionPaint(i, colors[i % colors.length]);
        }
        
        ChartPanel ChartPanel = new ChartPanel(pieChart);
        EmptyPanelTopLeft.removeAll();
        EmptyPanelTopLeft.add(ChartPanel, BorderLayout.CENTER);
        EmptyPanelTopLeft.validate();
    }
    
    public void ope() {
        ResultSet rs = null;
        try {
            DBConnect db = new DBConnect();
            rs = db.getReminder(UserDatabase.key);
            
            if (rs.next()) {
                String remind = rs.getString("reminder");
                jTextArea1.setText(remind);
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BottomProfileUserHome;
    private javax.swing.JLabel DateHomePanel;
    private javax.swing.JPanel DocumentButton;
    private javax.swing.JComboBox<String> DocumentCombobox;
    private javax.swing.JLabel EmailUser;
    private javax.swing.JPanel EmptyPanelBottomLeft;
    private javax.swing.JPanel EmptyPanelBottomRight;
    private javax.swing.JPanel EmptyPanelTopLeft;
    private javax.swing.JPanel EmptyPanelTopRight;
    private javax.swing.JLabel HereWhatGoing;
    private javax.swing.JLabel IconBellHome;
    private javax.swing.JLabel IconBlue13;
    private javax.swing.JLabel IconBlue14;
    private javax.swing.JLabel IconDarkblue13;
    private javax.swing.JLabel IconDocument;
    private javax.swing.JLabel IconRed1;
    private javax.swing.JLabel LabelNumberBlue;
    private javax.swing.JLabel LabelNumberDarkblue13;
    private javax.swing.JLabel LabelNumberRed1;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel NavBarHome;
    private javax.swing.JPanel NumberPanelBlue;
    private javax.swing.JPanel NumberPanelDarkblue13;
    private javax.swing.JPanel NumberPanelRed1;
    private javax.swing.JLabel NumberUserHome;
    private javax.swing.JLabel ProfielUserHome;
    private javax.swing.JTextField TextBlue;
    private javax.swing.JTextField TextDarkblue13;
    private javax.swing.JTextField TextRed1;
    private javax.swing.JPanel TopProfileHome;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel WelcomebackUsername;
    private javax.swing.JLabel WelcomebackUsername1;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonProject;
    private javax.swing.JButton jButtonSetting;
    private javax.swing.JButton jButtonTax;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbuttonReporting;
    private javax.swing.JLabel usethisDashboard;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        ResultSet rs = null;
        try {
            DBConnect db = new DBConnect();
            rs = db.getReminder(UserDatabase.key);
            
            if (rs.next()) {
                String remind = rs.getString("reminder");
                jTextArea1.setText(remind);
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void windowClosing(WindowEvent e) {
        String reminderText = jTextArea1.getText();

        try {
            DBConnect db = new DBConnect();
            db.updateReminder(UserDatabase.key, reminderText);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {}

    @Override
    public void windowDeiconified(WindowEvent e) {}

    @Override
    public void windowActivated(WindowEvent e) {}

    @Override
    public void windowDeactivated(WindowEvent e) {}
}
