package project;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Calendar;  
import javax.swing.UIManager;
import org.jfree.chart.*;
import java.util.Date;  
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author oatsu
 */
public class Report extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        setLocationRelativeTo(null);
        showYear();
        showIncome();
        showExpense();
        showTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ReportMainPanel = new javax.swing.JPanel();
        NavBarPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usethisDashboard = new javax.swing.JLabel();
        LogoIconLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserName = new javax.swing.JLabel();
        EmailUser = new javax.swing.JLabel();
        BottomProfileUserReporting = new javax.swing.JLabel();
        DocumentPanelButton = new javax.swing.JPanel();
        IconDocument = new javax.swing.JLabel();
        Document = new javax.swing.JComboBox<>();
        jButtonHome = new javax.swing.JButton();
        jButtonProject = new javax.swing.JButton();
        jButtonReporting = new javax.swing.JButton();
        jButtonUsers = new javax.swing.JButton();
        jButtonTax = new javax.swing.JButton();
        jButtonSetting = new javax.swing.JButton();
        ReportDashboard = new javax.swing.JPanel();
        ReportingOverview = new javax.swing.JLabel();
        IconbellReport = new javax.swing.JLabel();
        DateLabelReport = new javax.swing.JLabel();
        PanelTopProfileReport = new javax.swing.JPanel();
        TopProfileUser = new javax.swing.JLabel();
        ProfileNumber = new javax.swing.JLabel();
        YourbusinessPanel = new javax.swing.JPanel();
        YouBusinessReportLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        ProfitPanel = new javax.swing.JPanel();
        ProfitLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        IncomeLabel3 = new javax.swing.JLabel();
        IncomePanel = new javax.swing.JPanel();
        IncomeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IncomeLabel1 = new javax.swing.JLabel();
        ExpensesPanel = new javax.swing.JPanel();
        ExpensesLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        IncomeLabel2 = new javax.swing.JLabel();
        EfficiencyPanelLeft = new javax.swing.JPanel();
        EfficiencyPanelLeft1 = new javax.swing.JPanel();
        EfficiencyLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        EfficiencyPanelRight = new javax.swing.JPanel();
        EfficiencyLabel = new javax.swing.JLabel();
        ProfitabilityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        NavBarPanel.setBackground(new java.awt.Color(255, 255, 255));
        NavBarPanel.setPreferredSize(new java.awt.Dimension(340, 1020));

        jSeparator1.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator1.setForeground(new java.awt.Color(136, 136, 136));

        usethisDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usethisDashboard.setText("Usethis Dashboard");

        jSeparator2.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator2.setForeground(new java.awt.Color(136, 136, 136));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserName.setText("Username");

        EmailUser.setForeground(new java.awt.Color(136, 136, 136));
        EmailUser.setText("Email");

        DocumentPanelButton.setBackground(new java.awt.Color(255, 255, 255));

        IconDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_page-edit.png"))); // NOI18N

        Document.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Document.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Quotation", "Recipt" }));
        Document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DocumentPanelButtonLayout = new javax.swing.GroupLayout(DocumentPanelButton);
        DocumentPanelButton.setLayout(DocumentPanelButtonLayout);
        DocumentPanelButtonLayout.setHorizontalGroup(
            DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(IconDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DocumentPanelButtonLayout.setVerticalGroup(
            DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Document)
                    .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(IconDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png"))); // NOI18N
        jButtonHome.setText("  Home");
        jButtonHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonProject.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_app-window.png"))); // NOI18N
        jButtonProject.setText("  Project");
        jButtonProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjectActionPerformed(evt);
            }
        });

        jButtonReporting.setBackground(new java.awt.Color(224, 227, 232));
        jButtonReporting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonReporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_stats-report.png"))); // NOI18N
        jButtonReporting.setText("  Reporting");
        jButtonReporting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonReporting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportingActionPerformed(evt);
            }
        });

        jButtonUsers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_user-square.png"))); // NOI18N
        jButtonUsers.setText("  Users");
        jButtonUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonUsers.setHideActionText(true);
        jButtonUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jButtonTax.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_calculator.png"))); // NOI18N
        jButtonTax.setText("  Tax");
        jButtonTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonTax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxActionPerformed(evt);
            }
        });

        jButtonSetting.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_settings.png"))); // NOI18N
        jButtonSetting.setText("  Setting");
        jButtonSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarPanelLayout = new javax.swing.GroupLayout(NavBarPanel);
        NavBarPanel.setLayout(NavBarPanelLayout);
        NavBarPanelLayout.setHorizontalGroup(
            NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarPanelLayout.createSequentialGroup()
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                        .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LogoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usethisDashboard))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(BottomProfileUserReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserName)
                                    .addComponent(EmailUser))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonReporting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(NavBarPanelLayout.createSequentialGroup()
                                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DocumentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        NavBarPanelLayout.setVerticalGroup(
            NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarPanelLayout.createSequentialGroup()
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LogoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usethisDashboard)
                        .addGap(42, 42, 42)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DocumentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailUser))
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BottomProfileUserReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        ReportDashboard.setBackground(new java.awt.Color(236, 239, 243));

        ReportingOverview.setBackground(new java.awt.Color(255, 255, 255));
        ReportingOverview.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        ReportingOverview.setText("Reporting Overview");

        IconbellReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ph_bell.png"))); // NOI18N

        DateLabelReport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DateLabelReport.setForeground(new java.awt.Color(136, 136, 136));
        DateLabelReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circum_calendar-date.png"))); // NOI18N
        DateLabelReport.setText("Friday, July 10,2024");

        PanelTopProfileReport.setBackground(new java.awt.Color(255, 255, 255));

        TopProfileUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ellipse 2 (1).png"))); // NOI18N

        ProfileNumber.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ProfileNumber.setText("Number");

        javax.swing.GroupLayout PanelTopProfileReportLayout = new javax.swing.GroupLayout(PanelTopProfileReport);
        PanelTopProfileReport.setLayout(PanelTopProfileReportLayout);
        PanelTopProfileReportLayout.setHorizontalGroup(
            PanelTopProfileReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopProfileReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopProfileUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ProfileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelTopProfileReportLayout.setVerticalGroup(
            PanelTopProfileReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopProfileReportLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TopProfileUser)
                .addGap(18, 18, 18))
            .addGroup(PanelTopProfileReportLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ProfileNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        YourbusinessPanel.setBackground(new java.awt.Color(255, 255, 255));
        YourbusinessPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        YouBusinessReportLabel.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        YouBusinessReportLabel.setText("Your Business Report");

        jSeparator4.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator4.setForeground(new java.awt.Color(136, 136, 136));

        ProfitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProfitPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ProfitLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ProfitLabel.setText("Profit or loss");

        jPanel2.setLayout(new java.awt.BorderLayout());

        IncomeLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        IncomeLabel3.setText("0");

        javax.swing.GroupLayout ProfitPanelLayout = new javax.swing.GroupLayout(ProfitPanel);
        ProfitPanel.setLayout(ProfitPanelLayout);
        ProfitPanelLayout.setHorizontalGroup(
            ProfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ProfitPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ProfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IncomeLabel3)
                    .addComponent(ProfitLabel))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        ProfitPanelLayout.setVerticalGroup(
            ProfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IncomeLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        IncomePanel.setBackground(new java.awt.Color(255, 255, 255));
        IncomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        IncomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        IncomeLabel.setText("Income");

        jPanel1.setLayout(new java.awt.BorderLayout());

        IncomeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        IncomeLabel1.setText("0");

        javax.swing.GroupLayout IncomePanelLayout = new javax.swing.GroupLayout(IncomePanel);
        IncomePanel.setLayout(IncomePanelLayout);
        IncomePanelLayout.setHorizontalGroup(
            IncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(IncomePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(IncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IncomeLabel)
                    .addComponent(IncomeLabel1))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        IncomePanelLayout.setVerticalGroup(
            IncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IncomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IncomeLabel1)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        ExpensesPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExpensesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ExpensesLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ExpensesLabel.setText("Expenses");

        jPanel3.setLayout(new java.awt.BorderLayout());

        IncomeLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        IncomeLabel2.setText("0");

        javax.swing.GroupLayout ExpensesPanelLayout = new javax.swing.GroupLayout(ExpensesPanel);
        ExpensesPanel.setLayout(ExpensesPanelLayout);
        ExpensesPanelLayout.setHorizontalGroup(
            ExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ExpensesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IncomeLabel2)
                    .addComponent(ExpensesLabel))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        ExpensesPanelLayout.setVerticalGroup(
            ExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExpensesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IncomeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        EfficiencyPanelLeft.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyPanelLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        EfficiencyPanelLeft1.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyPanelLeft1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        EfficiencyLabel3.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EfficiencyLabel3.setText("Operating Expense");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout EfficiencyPanelLeft1Layout = new javax.swing.GroupLayout(EfficiencyPanelLeft1);
        EfficiencyPanelLeft1.setLayout(EfficiencyPanelLeft1Layout);
        EfficiencyPanelLeft1Layout.setHorizontalGroup(
            EfficiencyPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EfficiencyPanelLeft1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EfficiencyPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(EfficiencyPanelLeft1Layout.createSequentialGroup()
                        .addComponent(EfficiencyLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EfficiencyPanelLeft1Layout.setVerticalGroup(
            EfficiencyPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EfficiencyPanelLeft1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EfficiencyLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EfficiencyPanelLeftLayout = new javax.swing.GroupLayout(EfficiencyPanelLeft);
        EfficiencyPanelLeft.setLayout(EfficiencyPanelLeftLayout);
        EfficiencyPanelLeftLayout.setHorizontalGroup(
            EfficiencyPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EfficiencyPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EfficiencyPanelLeft1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EfficiencyPanelLeftLayout.setVerticalGroup(
            EfficiencyPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EfficiencyPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EfficiencyPanelLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EfficiencyPanelRight.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyPanelRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout EfficiencyPanelRightLayout = new javax.swing.GroupLayout(EfficiencyPanelRight);
        EfficiencyPanelRight.setLayout(EfficiencyPanelRightLayout);
        EfficiencyPanelRightLayout.setHorizontalGroup(
            EfficiencyPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EfficiencyPanelRightLayout.setVerticalGroup(
            EfficiencyPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        EfficiencyLabel.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyLabel.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        EfficiencyLabel.setText("Efficiency");

        ProfitabilityLabel.setBackground(new java.awt.Color(255, 255, 255));
        ProfitabilityLabel.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        ProfitabilityLabel.setText("Profitability");

        javax.swing.GroupLayout YourbusinessPanelLayout = new javax.swing.GroupLayout(YourbusinessPanel);
        YourbusinessPanel.setLayout(YourbusinessPanelLayout);
        YourbusinessPanelLayout.setHorizontalGroup(
            YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                        .addComponent(YouBusinessReportLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YourbusinessPanelLayout.createSequentialGroup()
                        .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                                .addComponent(ProfitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IncomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EfficiencyPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EfficiencyPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExpensesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                        .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfitabilityLabel)
                            .addComponent(EfficiencyLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        YourbusinessPanelLayout.setVerticalGroup(
            YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(YouBusinessReportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ProfitabilityLabel)
                .addGap(26, 26, 26)
                .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IncomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpensesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(EfficiencyLabel)
                .addGap(31, 31, 31)
                .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EfficiencyPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EfficiencyPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout ReportDashboardLayout = new javax.swing.GroupLayout(ReportDashboard);
        ReportDashboard.setLayout(ReportDashboardLayout);
        ReportDashboardLayout.setHorizontalGroup(
            ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReportDashboardLayout.createSequentialGroup()
                        .addComponent(IconbellReport)
                        .addGap(18, 18, 18)
                        .addComponent(PanelTopProfileReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(ReportDashboardLayout.createSequentialGroup()
                        .addComponent(ReportingOverview)
                        .addGap(576, 576, 576)
                        .addComponent(DateLabelReport)))
                .addGap(39, 39, 39))
            .addGroup(ReportDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YourbusinessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ReportDashboardLayout.setVerticalGroup(
            ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportDashboardLayout.createSequentialGroup()
                        .addComponent(PanelTopProfileReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportDashboardLayout.createSequentialGroup()
                        .addComponent(IconbellReport)
                        .addGap(31, 31, 31)))
                .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLabelReport)
                    .addComponent(ReportingOverview))
                .addGap(31, 31, 31)
                .addComponent(YourbusinessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout ReportMainPanelLayout = new javax.swing.GroupLayout(ReportMainPanel);
        ReportMainPanel.setLayout(ReportMainPanelLayout);
        ReportMainPanelLayout.setHorizontalGroup(
            ReportMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportMainPanelLayout.createSequentialGroup()
                .addComponent(NavBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ReportMainPanelLayout.setVerticalGroup(
            ReportMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportMainPanelLayout.createSequentialGroup()
                .addGroup(ReportMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReportDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NavBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jScrollPane1.setViewportView(ReportMainPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentActionPerformed
        // TODO add your handling code here:
        String selectedDocument = (String) Document.getSelectedItem();
        switch (selectedDocument) {
        case "Document":
            break;
        case "Quotation":
            openQuotition();
            break;
        case "Recipt":
            openReceipt();
            break;
        default:
            break;
    }
    }//GEN-LAST:event_DocumentActionPerformed
    private void openQuotition() {
        Quotition registerForm = new Quotition();
        registerForm.setVisible(true);
    }

    private void openReceipt() {
        Receipt registerForm = new Receipt();
        registerForm.setVisible(true);
    }
    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jButtonTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaxActionPerformed
        // TODO add your handling code here:
        TaxCalculate registerForm = new TaxCalculate();
        registerForm.setVisible(true);
        jButtonTax.addActionListener(new Report());
        TaxCalculate tx = new TaxCalculate();
        tx.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTaxActionPerformed

    private void jButtonProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjectActionPerformed
        // TODO add your handling code here:
          Project registerForm = new Project();
        registerForm.setVisible(true);
        jButtonProject.addActionListener(new Report());
        dispose();
    }//GEN-LAST:event_jButtonProjectActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Home registerForm = new Home();
        registerForm.setVisible(true);
        jButtonHome.addActionListener(new Report());
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportingActionPerformed
        // TODO add your handling code here:
        Report registerForm = new Report();
        registerForm.setVisible(true);
        jButtonReporting.addActionListener(new Report());
        dispose();
    }//GEN-LAST:event_jButtonReportingActionPerformed

    private void jButtonSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSettingActionPerformed

    
    public void showYear() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        ResultSet rs = null;
        Calendar calendar = Calendar.getInstance();
        String year = String.valueOf(calendar.get(Calendar.YEAR));
        int prof = 0;
        
        
        try {
            DBConnect db = new DBConnect();
            rs = db.getAnnualReport(UserDatabase.key, year);
            
            if (rs.next()) {
                 String yr = rs.getString("year");
                 dataset.setValue(Double.parseDouble(rs.getString("income")), "2024", "Income " + yr);
                 dataset.setValue(Double.parseDouble(rs.getString("expense")), "2024", "Expense " + yr);
                 
                 prof = (Integer.parseInt(rs.getString("income")) - Integer.parseInt(rs.getString("expense")));
                 IncomeLabel3.setText(String.valueOf(prof));
            }
            JFreeChart Chart = ChartFactory.createBarChart("Annual Sales", "Year", "", dataset, PlotOrientation.VERTICAL.VERTICAL, false, true, false);
    
        CategoryPlot Category = Chart.getCategoryPlot();
        Category.setBackgroundPaint(Color.white);
        
        BarRenderer Renderer = (BarRenderer) Category.getRenderer();
        Color ChartColor = new Color(74, 134, 228);
        Renderer.setSeriesPaint(0, ChartColor);
        
        ChartPanel ChartPanel = new ChartPanel(Chart);
        jPanel2.removeAll();
        jPanel2.add(ChartPanel, BorderLayout.CENTER);
        jPanel2.validate();
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    
public void showIncome() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    ResultSet rs = null;
    double[] months = new double[5];
    int inc = 0;
    String[] monthNames = {"jan_income", "feb_income", "mar_income", "apr_income", "may_income", "june_income", "july_income", "aug_income", "sep_income", "oct_income", "nov_income", "dec_income"};
    String[] monthNames2 = {"Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"};
    LocalDate currentDate = LocalDate.now();
    int currentMonthIndex = currentDate.getMonthValue() - 1;

    try {
        DBConnect db = new DBConnect();
        rs = db.getMonthIncome(UserDatabase.key);

        while (rs.next()) {
            for (int i = currentMonthIndex, count = 0; count < 5; i--, count++) {
                if (i < 0)
                    i = 11;
                months[count] += Double.parseDouble(rs.getString(monthNames[i]));
            }
            
            for (int i = 0; i < 12; i++) {
                inc += Double.parseDouble(rs.getString(monthNames[i]));
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    for (int i = 0; i < 5; i++) {
        int monthIndex = currentMonthIndex - i;
        if (monthIndex < 0)
            monthIndex += 12;
        dataset.setValue(months[i], "amount", monthNames2[monthIndex]);
    }
    
    IncomeLabel2.setText(String.valueOf(inc));

    JFreeChart chart = ChartFactory.createBarChart("Income", "Month", "Amount", dataset, PlotOrientation.VERTICAL, false, true, false);

    CategoryPlot category = chart.getCategoryPlot();
    category.setBackgroundPaint(Color.white);

    BarRenderer renderer = (BarRenderer) category.getRenderer();
    Color chartColor = new Color(74, 134, 228);
    renderer.setSeriesPaint(0, chartColor);

    ChartPanel chartPanel = new ChartPanel(chart);
    jPanel1.removeAll();
    jPanel1.add(chartPanel, BorderLayout.CENTER);
    jPanel1.validate();
}
  
public void showExpense() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    ResultSet rs = null;
    double[] months = new double[5];
    int expe = 0;
    String[] monthNames = {"jan_expense", "feb_expense", "mar_expense", "apr_expense", "may_expense", "june_expense", "july_expense", "aug_expense", "sep_expense", "oct_expense", "nov_expense", "dec_expense"};
    String[] monthNames2 = {"Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"};
    LocalDate currentDate = LocalDate.now();
    int currentMonthIndex = currentDate.getMonthValue() - 1;

    try {
        DBConnect db = new DBConnect();
        rs = db.getMonthExpense(UserDatabase.key);

        while (rs.next()) {
            for (int i = currentMonthIndex, count = 0; count < 5; i--, count++) {
                if (i < 0)
                    i = 11;
                months[count] += Double.parseDouble(rs.getString(monthNames[i]));
            }
            
            for (int i = 0; i < 12; i++) {
                expe += Double.parseDouble(rs.getString(monthNames[i]));
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    for (int i = 0; i < 5; i++) {
        int monthIndex = currentMonthIndex - i;
        if (monthIndex < 0)
            monthIndex += 12;
        dataset.setValue(months[i], "amount", monthNames2[monthIndex]);
    }
   
    IncomeLabel1.setText(String.valueOf(expe));
    JFreeChart chart = ChartFactory.createBarChart("Expense", "Month", "Amount", dataset, PlotOrientation.VERTICAL, false, true, false);

    CategoryPlot category = chart.getCategoryPlot();
    category.setBackgroundPaint(Color.white);

    BarRenderer renderer = (BarRenderer) category.getRenderer();
    Color chartColor = new Color(74, 134, 228);
    renderer.setSeriesPaint(0, chartColor);

    ChartPanel chartPanel = new ChartPanel(chart);
    jPanel3.removeAll();
    jPanel3.add(chartPanel, BorderLayout.CENTER);
    jPanel3.validate();
}

public void showTable() {
    jTable2.setTableHeader(null);
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    Calendar calendar = Calendar.getInstance();
    int currentYear = calendar.get(Calendar.YEAR);
    jTable2.getColumnModel().getColumn(1).setHeaderValue("Jan 1 - Dec " + String.valueOf(currentYear));
    jTable2.getColumnModel().getColumn(2).setHeaderValue("Jan 1 - Dec " + String.valueOf(currentYear - 1));
    try {
        DBConnect db = new DBConnect();
        ResultSet rs = db.getItemExpenseByYear(UserDatabase.key, currentYear);

        while (rs.next()) {
            String name = rs.getString("name");
            String year = rs.getString("year");
            String expense = rs.getString("expense");
            int lastYear = Integer.parseInt(year) - 1;
            String lastYearExpense = getLastYearExpense(name, lastYear);

            Object[] rowData = {name, expense, lastYearExpense};
            model.addRow(rowData);
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

private String getLastYearExpense(String name, int lastYear) {
    try {
        DBConnect db = new DBConnect();
        ResultSet rs = db.getItemExpenseByYear(UserDatabase.key, lastYear);

        while (rs.next()) {
            if (name.equals(rs.getString("name"))) {
                return rs.getString("expense");
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    return "N/A";
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BottomProfileUserReporting;
    private javax.swing.JLabel DateLabelReport;
    private javax.swing.JComboBox<String> Document;
    private javax.swing.JPanel DocumentPanelButton;
    private javax.swing.JLabel EfficiencyLabel;
    private javax.swing.JLabel EfficiencyLabel3;
    private javax.swing.JPanel EfficiencyPanelLeft;
    private javax.swing.JPanel EfficiencyPanelLeft1;
    private javax.swing.JPanel EfficiencyPanelRight;
    private javax.swing.JLabel EmailUser;
    private javax.swing.JLabel ExpensesLabel;
    private javax.swing.JPanel ExpensesPanel;
    private javax.swing.JLabel IconDocument;
    private javax.swing.JLabel IconbellReport;
    private javax.swing.JLabel IncomeLabel;
    private javax.swing.JLabel IncomeLabel1;
    private javax.swing.JLabel IncomeLabel2;
    private javax.swing.JLabel IncomeLabel3;
    private javax.swing.JPanel IncomePanel;
    private javax.swing.JLabel LogoIconLabel;
    private javax.swing.JPanel NavBarPanel;
    private javax.swing.JPanel PanelTopProfileReport;
    private javax.swing.JLabel ProfileNumber;
    private javax.swing.JLabel ProfitLabel;
    private javax.swing.JPanel ProfitPanel;
    private javax.swing.JLabel ProfitabilityLabel;
    private javax.swing.JPanel ReportDashboard;
    private javax.swing.JPanel ReportMainPanel;
    private javax.swing.JLabel ReportingOverview;
    private javax.swing.JLabel TopProfileUser;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel YouBusinessReportLabel;
    private javax.swing.JPanel YourbusinessPanel;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonProject;
    private javax.swing.JButton jButtonReporting;
    private javax.swing.JButton jButtonSetting;
    private javax.swing.JButton jButtonTax;
    private javax.swing.JButton jButtonUsers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel usethisDashboard;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
