/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oatsu
 */
public class TaxCalculate extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form TaxCalculate
     */
    public TaxCalculate() {
        initComponents();
        setLocationRelativeTo(null);
        showTax();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TaxCalMainPanel = new javax.swing.JPanel();
        NavBarPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usethisDashboard = new javax.swing.JLabel();
        LogoIconLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserName = new javax.swing.JLabel();
        EmailUser = new javax.swing.JLabel();
        BottomProfileUserReporting = new javax.swing.JLabel();
        DocumentPanelButton = new javax.swing.JPanel();
        IconDocument = new javax.swing.JLabel();
        Document = new javax.swing.JComboBox<>();
        jButtonHome = new javax.swing.JButton();
        jButtonProject = new javax.swing.JButton();
        jButtonReporting = new javax.swing.JButton();
        jButtonUsers = new javax.swing.JButton();
        jButtonTax = new javax.swing.JButton();
        jButtonSetting = new javax.swing.JButton();
        TaxCalDashboard = new javax.swing.JPanel();
        TaxCalculateLabel = new javax.swing.JLabel();
        IconbellTax = new javax.swing.JLabel();
        DateLabelTax = new javax.swing.JLabel();
        PanelTopProfileTax = new javax.swing.JPanel();
        TopProfileUser = new javax.swing.JLabel();
        ProfileNumber = new javax.swing.JLabel();
        TaxCalculatePanel = new javax.swing.JPanel();
        IncomPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        IncomLabel = new javax.swing.JLabel();
        AnnualSalesLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        TaxMoneyToBePaidLabel = new javax.swing.JLabel();
        MoneyToPaidLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(224, 227, 232));
        setPreferredSize(new java.awt.Dimension(1440, 1020));

        TaxCalMainPanel.setLayout(new java.awt.BorderLayout());

        NavBarPanel.setBackground(new java.awt.Color(255, 255, 255));
        NavBarPanel.setPreferredSize(new java.awt.Dimension(340, 1020));

        jSeparator1.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator1.setForeground(new java.awt.Color(136, 136, 136));

        usethisDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usethisDashboard.setText("Usethis Dashboard");

        jSeparator2.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator2.setForeground(new java.awt.Color(136, 136, 136));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserName.setText("Username");

        EmailUser.setForeground(new java.awt.Color(136, 136, 136));
        EmailUser.setText("Email");

        DocumentPanelButton.setBackground(new java.awt.Color(255, 255, 255));

        IconDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_page-edit.png"))); // NOI18N

        Document.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Document.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Quotation", "Recipt" }));
        Document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DocumentPanelButtonLayout = new javax.swing.GroupLayout(DocumentPanelButton);
        DocumentPanelButton.setLayout(DocumentPanelButtonLayout);
        DocumentPanelButtonLayout.setHorizontalGroup(
            DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(IconDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DocumentPanelButtonLayout.setVerticalGroup(
            DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Document)
                    .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(IconDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png"))); // NOI18N
        jButtonHome.setText("  Home");
        jButtonHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonProject.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_app-window.png"))); // NOI18N
        jButtonProject.setText("  Project");
        jButtonProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjectActionPerformed(evt);
            }
        });

        jButtonReporting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonReporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_stats-report.png"))); // NOI18N
        jButtonReporting.setText("  Reporting");
        jButtonReporting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonReporting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportingActionPerformed(evt);
            }
        });

        jButtonUsers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_user-square.png"))); // NOI18N
        jButtonUsers.setText("  Users");
        jButtonUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonUsers.setHideActionText(true);
        jButtonUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jButtonTax.setBackground(new java.awt.Color(224, 227, 232));
        jButtonTax.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_calculator.png"))); // NOI18N
        jButtonTax.setText("  Tax");
        jButtonTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonTax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxActionPerformed(evt);
            }
        });

        jButtonSetting.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_settings.png"))); // NOI18N
        jButtonSetting.setText("  Setting");
        jButtonSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarPanelLayout = new javax.swing.GroupLayout(NavBarPanel);
        NavBarPanel.setLayout(NavBarPanelLayout);
        NavBarPanelLayout.setHorizontalGroup(
            NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarPanelLayout.createSequentialGroup()
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                        .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LogoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usethisDashboard))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(BottomProfileUserReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserName)
                                    .addComponent(EmailUser))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonReporting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(NavBarPanelLayout.createSequentialGroup()
                                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DocumentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        NavBarPanelLayout.setVerticalGroup(
            NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarPanelLayout.createSequentialGroup()
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LogoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usethisDashboard)
                        .addGap(42, 42, 42)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DocumentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailUser))
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BottomProfileUserReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        TaxCalMainPanel.add(NavBarPanel, java.awt.BorderLayout.WEST);

        TaxCalDashboard.setBackground(new java.awt.Color(236, 239, 243));

        TaxCalculateLabel.setBackground(new java.awt.Color(255, 255, 255));
        TaxCalculateLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TaxCalculateLabel.setText("Tax Calculate");

        IconbellTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ph_bell.png"))); // NOI18N

        DateLabelTax.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DateLabelTax.setForeground(new java.awt.Color(136, 136, 136));
        DateLabelTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circum_calendar-date.png"))); // NOI18N
        DateLabelTax.setText("Friday, July 10,2024");

        PanelTopProfileTax.setBackground(new java.awt.Color(255, 255, 255));

        TopProfileUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ellipse 2 (1).png"))); // NOI18N

        ProfileNumber.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ProfileNumber.setText("Number");

        javax.swing.GroupLayout PanelTopProfileTaxLayout = new javax.swing.GroupLayout(PanelTopProfileTax);
        PanelTopProfileTax.setLayout(PanelTopProfileTaxLayout);
        PanelTopProfileTaxLayout.setHorizontalGroup(
            PanelTopProfileTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopProfileTaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopProfileUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ProfileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelTopProfileTaxLayout.setVerticalGroup(
            PanelTopProfileTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopProfileTaxLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TopProfileUser)
                .addGap(18, 18, 18))
            .addGroup(PanelTopProfileTaxLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ProfileNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TaxCalculatePanel.setBackground(new java.awt.Color(255, 255, 255));
        TaxCalculatePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        IncomPanel.setBackground(new java.awt.Color(255, 255, 255));
        IncomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        IncomLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IncomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IncomLabel.setText("Income");

        AnnualSalesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AnnualSalesLabel.setText("Annual Sales");

        PriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PriceLabel.setText("฿ 1,000,000");

        javax.swing.GroupLayout IncomPanelLayout = new javax.swing.GroupLayout(IncomPanel);
        IncomPanel.setLayout(IncomPanelLayout);
        IncomPanelLayout.setHorizontalGroup(
            IncomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(IncomPanelLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(IncomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(IncomPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(AnnualSalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        IncomPanelLayout.setVerticalGroup(
            IncomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomPanelLayout.createSequentialGroup()
                .addGroup(IncomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IncomPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(IncomPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IncomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(IncomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnualSalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        TaxMoneyToBePaidLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TaxMoneyToBePaidLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaxMoneyToBePaidLabel.setText("Tax Money To Be Paid");

        MoneyToPaidLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        MoneyToPaidLabel.setForeground(new java.awt.Color(239, 116, 109));
        MoneyToPaidLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MoneyToPaidLabel.setText("฿ 88,400");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Group 42.png"))); // NOI18N

        javax.swing.GroupLayout TaxCalculatePanelLayout = new javax.swing.GroupLayout(TaxCalculatePanel);
        TaxCalculatePanel.setLayout(TaxCalculatePanelLayout);
        TaxCalculatePanelLayout.setHorizontalGroup(
            TaxCalculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxCalculatePanelLayout.createSequentialGroup()
                .addGroup(TaxCalculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaxCalculatePanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(IncomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TaxCalculatePanelLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(TaxMoneyToBePaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TaxCalculatePanelLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(MoneyToPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TaxCalculatePanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        TaxCalculatePanelLayout.setVerticalGroup(
            TaxCalculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaxCalculatePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(TaxMoneyToBePaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoneyToPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(IncomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout TaxCalDashboardLayout = new javax.swing.GroupLayout(TaxCalDashboard);
        TaxCalDashboard.setLayout(TaxCalDashboardLayout);
        TaxCalDashboardLayout.setHorizontalGroup(
            TaxCalDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxCalDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaxCalDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaxCalDashboardLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(TaxCalDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaxCalDashboardLayout.createSequentialGroup()
                                .addGroup(TaxCalDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(TaxCalDashboardLayout.createSequentialGroup()
                                        .addComponent(IconbellTax)
                                        .addGap(18, 18, 18)
                                        .addComponent(PanelTopProfileTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addComponent(DateLabelTax))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaxCalDashboardLayout.createSequentialGroup()
                                .addComponent(TaxCalculatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(TaxCalDashboardLayout.createSequentialGroup()
                        .addComponent(TaxCalculateLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TaxCalDashboardLayout.setVerticalGroup(
            TaxCalDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxCalDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TaxCalDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaxCalDashboardLayout.createSequentialGroup()
                        .addComponent(PanelTopProfileTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaxCalDashboardLayout.createSequentialGroup()
                        .addComponent(IconbellTax)
                        .addGap(31, 31, 31)))
                .addComponent(DateLabelTax)
                .addGap(15, 15, 15)
                .addComponent(TaxCalculateLabel)
                .addGap(18, 18, 18)
                .addComponent(TaxCalculatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        TaxCalMainPanel.add(TaxCalDashboard, java.awt.BorderLayout.CENTER);

        getContentPane().add(TaxCalMainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentActionPerformed
        // TODO add your handling code here:
        String selectedDocument = (String) Document.getSelectedItem();
        switch (selectedDocument) {
        case "Document":
            break;
        case "Quotation":
            openQuotition();
            break;
        case "Recipt":
            openReceipt();
            break;
        default:
            break;
    }
    }//GEN-LAST:event_DocumentActionPerformed
    
    private void openQuotition() {
        Quotition registerForm = new Quotition();
        registerForm.setVisible(true);
    }
    private void openReceipt() {
        Receipt registerForm = new Receipt();
        registerForm.setVisible(true);
    }
    
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Home registerForm = new Home();
        registerForm.setVisible(true);
        jButtonHome.addActionListener(new TaxCalculate());
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjectActionPerformed
        // TODO add your handling code here:
        Project registerForm = new Project();
        registerForm.setVisible(true);
        jButtonProject.addActionListener(new TaxCalculate());
        Project pj = new Project();
        pj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonProjectActionPerformed

    private void jButtonReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportingActionPerformed
        // TODO add your handling code here:
        Report pj = new Report();
           Report registerForm = new Report();
        registerForm.setVisible(true);
        jButtonReporting.addActionListener(new TaxCalculate());
        pj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReportingActionPerformed

    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jButtonTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaxActionPerformed
        // TODO add your handling code here:
        TaxCalculate registerForm = new TaxCalculate();
        registerForm.setVisible(true);
        jButtonTax.addActionListener(new TaxCalculate());
        dispose();
    }//GEN-LAST:event_jButtonTaxActionPerformed

    private void jButtonSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSettingActionPerformed

public void showTax() {
    Calendar calendar = Calendar.getInstance();
    int currentYear = calendar.get(Calendar.YEAR);
    int tax = 0;
    try {
        DBConnect db = new DBConnect();
        ResultSet rs = db.getProfit(UserDatabase.key, currentYear);

        while (rs.next()) {
            String name = rs.getString("income");
            int profit;
            profit = 291000;
            int temp = 0;
            
            if (profit > 150000) {
                profit -= 150000;
                temp = (int) (profit * 0.05);
                if (temp > 7500) {
                    temp = 7500;
                }
                tax += temp;
                temp = 0;
            }
            if (profit > 300000) {
                profit -= 300000;
                temp = (int) (profit * 0.10);
                if (temp > 20000) {
                    temp = 20000;
                }
                tax += temp;
                temp = 0;
            }
            if (profit > 500000) {
                profit -= 500000;
                temp = (int) (profit * 0.15);
                if (temp > 37500) {
                    temp = 37500;
                }
                tax += temp;
                temp = 0;
            }
            if (profit > 750000) {
                profit -= 750000;
                temp = (int) (profit * 0.20);
                if (temp > 50000) {
                    temp = 50000;
                }
                tax += temp;
                temp = 0;
            }
            if (profit > 1000000) {
                profit -= 1000000;
                temp = (int) (profit * 0.25);
                if (temp > 250000) {
                    temp = 250000;
                }
                tax += temp;
                temp = 0;
            }
            if (profit > 2000000) {
                profit -= 2000000;
                temp = (int) (profit * 0.30);
                if (temp > 900000) {
                    temp = 900000;
                }
                tax += temp;
                temp = 0;
            }
             if (profit > 5000000) {
                profit -= 5000000;
                temp = (int) (profit * 0.35);
                tax += temp;
                temp = 0;
            }
             MoneyToPaidLabel.setText(String.valueOf(tax));
        }
        CheckFunction<String> checkFunction = new CheckFunction<>();
        checkFunction.setContent("Complete");
        System.out.println("Function Status: " + checkFunction.getContent());
        
    } catch (Exception ex) {
        ex.printStackTrace();
        CheckFunction<String> checkFunction = new CheckFunction<>();
        checkFunction.setContent("Failed");
        System.out.println("Function Status: " + checkFunction.getContent());
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxCalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnnualSalesLabel;
    private javax.swing.JLabel BottomProfileUserReporting;
    private javax.swing.JLabel DateLabelTax;
    private javax.swing.JComboBox<String> Document;
    private javax.swing.JPanel DocumentPanelButton;
    private javax.swing.JLabel EmailUser;
    private javax.swing.JLabel IconDocument;
    private javax.swing.JLabel IconbellTax;
    private javax.swing.JLabel IncomLabel;
    private javax.swing.JPanel IncomPanel;
    private javax.swing.JLabel LogoIconLabel;
    private javax.swing.JLabel MoneyToPaidLabel;
    private javax.swing.JPanel NavBarPanel;
    private javax.swing.JPanel PanelTopProfileTax;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel ProfileNumber;
    private javax.swing.JPanel TaxCalDashboard;
    private javax.swing.JPanel TaxCalMainPanel;
    private javax.swing.JLabel TaxCalculateLabel;
    private javax.swing.JPanel TaxCalculatePanel;
    private javax.swing.JLabel TaxMoneyToBePaidLabel;
    private javax.swing.JLabel TopProfileUser;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonProject;
    private javax.swing.JButton jButtonReporting;
    private javax.swing.JButton jButtonSetting;
    private javax.swing.JButton jButtonTax;
    private javax.swing.JButton jButtonUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel usethisDashboard;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
